import type { Permission } from '@/lib/pos/types';

export const OWNER_PERMISSIONS: Permission[] = [
  'dashboard',
  'checkout',
  'add-product',
  'edit-product',
  'delete-product',
  'inventory',
  'adjust-stock',
  'give-discount',
  'void-sale',
  'reports',
  'credit-sales',
  'export-reports',
  'users',
  'settings',
  'customers',
  'vendors',
  'expenses',
  'refunds',
  'view-profit',
  'view-cost-price',
  'expiry-alerts',
  'manage-tax',
  'branches',
  'notifications',
  'sync-logs',
  'categories',
  'expense-heads',
];
