; Compile with Inno Setup on Windows after preparing installer/windows/payload.
; Required payloads:
;   payload/node/node.exe
;   payload/postgresql/bin/*, payload/postgresql/lib/*, payload/postgresql/share/*
; The application payload is generated by: npm run package:onprem

#define AppName "TOVAPOS On-Premise"
#define AppVersion "0.1.0"
#define AppPublisher "TOVAPOS"
#define AppExeName "TOVAPOS-Server.cmd"

[Setup]
AppId={{B0E4AE6C-1D6C-4B89-9B7D-5E6C1F0F40A1}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
DefaultDirName={autopf}\TOVAPOS
DefaultGroupName=TOVAPOS
OutputDir=..\..\installer-output
OutputBaseFilename=TOVAPOS-OnPremise-Setup
SetupIconFile=..\..\public\favicon.ico
UninstallDisplayIcon={app}\app\public\favicon.ico
Compression=lzma2
SolidCompression=yes
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
WizardStyle=modern
DisableProgramGroupPage=yes
PrivilegesRequiredOverridesAllowed=dialog
MinVersion=10.0

[Messages]
WelcomeLabel1=Welcome to TOVAPOS On-Premise
WelcomeLabel2=This guided setup will install your local POS server, secure database, backup tools, and LAN access. You will be shown what each step does before anything is changed.
FinishedHeadingLabel=TOVAPOS is ready
FinishedLabel=TOVAPOS has been installed on this computer. You can now open it locally or connect cashier computers on the same private network.

[Files]
Source: "..\..\onprem-dist\*"; DestDir: "{app}\app"; Flags: recursesubdirs ignoreversion
Source: "payload\node\node.exe"; DestDir: "{app}\runtime"; Flags: ignoreversion
Source: "payload\postgresql\*"; DestDir: "{app}\postgresql"; Flags: recursesubdirs ignoreversion
Source: "install-onprem.ps1"; DestDir: "{app}\installer"; Flags: ignoreversion
Source: "start-onprem.ps1"; DestDir: "{app}\installer"; Flags: ignoreversion

[Dirs]
Name: "{app}\data"
Name: "{app}\backups"

[Icons]
Name: "{group}\TOVAPOS Server"; Filename: "{app}\TOVAPOS-Server.cmd"; WorkingDir: "{app}"
Name: "{commondesktop}\TOVAPOS Server"; Filename: "{app}\TOVAPOS-Start.cmd"; WorkingDir: "{app}"
Name: "{commondesktop}\Open TOVAPOS"; Filename: "{app}\TOVAPOS-Start.cmd"; WorkingDir: "{app}"; IconFilename: "{app}\app\public\favicon.ico"

[Run]
Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\installer\install-onprem.ps1"" -InstallRoot ""{app}"""; Flags: waituntilterminated
Filename: "http://127.0.0.1:4028"; Description: "Open TOVAPOS"; Flags: postinstall shellexec skipifsilent

[UninstallRun]
Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -Command ""Stop-Service TOVAPOSPostgreSQL -ErrorAction SilentlyContinue"""; Flags: runhidden; RunOnceId: "StopTOVAPOSPostgreSQL"

[Registry]
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "TOVAPOS"; ValueData: "{app}\TOVAPOS-Start.cmd"; Flags: uninsdeletevalue
