#!/usr/bin/env node
import http from 'node:http';
import { spawnSync } from 'node:child_process';
const port=Number(process.env.TOVAPOS_PRINT_PORT||4318), printer=process.env.TOVAPOS_PRINTER_NAME||'';
const reply=(r,s,b)=>{r.writeHead(s,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'POST,GET,OPTIONS','Access-Control-Allow-Headers':'Content-Type'});r.end(JSON.stringify(b));};
const money=n=>Number(n||0).toFixed(2);
const receiptText=r=>{const a=['TOVAPOS',r.businessName||'','',r.transactionId||'',r.timestamp||'','Cashier: '+(r.cashier||''),'Payment: '+(r.paymentMethod||''),'--------------------------------'];for(const i of r.items||[])a.push(i.name+' x'+i.quantity+' '+money(i.unitPrice*i.quantity));a.push('--------------------------------','Subtotal: '+money(r.subtotal),'Tax: '+money(r.taxAmount),'TOTAL: '+money(r.amountPaid??r.grandTotal),'',r.footer||'Thank you.','');return a.join('\r\n');};
const defaultPrinter=()=>{ if(printer)return printer; if(process.platform==='win32')return spawnSync('powershell.exe',['-NoProfile','-Command','(Get-CimInstance Win32_Printer | ? Default).Name | select -First 1'],{encoding:'utf8'}).stdout.trim(); const result=spawnSync('lpstat',['-d'],{encoding:'utf8'}); return result.status===0?(result.stdout.match(/:\s*(.+)\s*$/)?.[1]||''):'';};
const send=(name,text)=>{ if(process.platform==='win32'){ const p=spawnSync('powershell.exe',['-NoProfile','-Command','param($n,$t);$t | Out-Printer -Name $n','-n',name,'-t',text],{encoding:'utf8'}); if(p.status)throw Error(p.stderr||'Windows printer rejected the receipt'); return; } const p=spawnSync('lp',['-d',name],{input:text,encoding:'utf8'}); if(p.status)throw Error(p.stderr||'CUPS could not print the receipt'); };
http.createServer((req,res)=>{if(req.method==='OPTIONS')return reply(res,204,{});if(req.method==='GET'&&req.url==='/health')return reply(res,200,{ok:true,printer:defaultPrinter(),platform:process.platform});if(req.method!=='POST'||req.url!=='/print')return reply(res,404,{ok:false});let b='';req.on('data',x=>b+=x);req.on('end',()=>{try{const x=JSON.parse(b),p=x.printerName||defaultPrinter();if(!p)throw Error('No printer configured. Set TOVAPOS_PRINTER_NAME.');const t=receiptText(x);send(p,t);reply(res,200,{ok:true,printer:p});}catch(e){reply(res,500,{ok:false,error:e.message});}})}).listen(port,'127.0.0.1',()=>console.log('TOVAPOS print bridge listening on '+port));
